version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - mongo
    environment:
      NODE_ENV: development
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - .:/app
      - /app/node_modules
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  mongo:
    image: mongo:6
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}